// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: axon/agent/v1/agent.proto

package types

import (
	fmt "fmt"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type AgentStatus int32

const (
	AgentStatus_AGENT_STATUS_UNSPECIFIED AgentStatus = 0
	AgentStatus_AGENT_STATUS_ONLINE      AgentStatus = 1
	AgentStatus_AGENT_STATUS_OFFLINE     AgentStatus = 2
	AgentStatus_AGENT_STATUS_SUSPENDED   AgentStatus = 3
)

var AgentStatus_name = map[int32]string{
	0: "AGENT_STATUS_UNSPECIFIED",
	1: "AGENT_STATUS_ONLINE",
	2: "AGENT_STATUS_OFFLINE",
	3: "AGENT_STATUS_SUSPENDED",
}

var AgentStatus_value = map[string]int32{
	"AGENT_STATUS_UNSPECIFIED": 0,
	"AGENT_STATUS_ONLINE":      1,
	"AGENT_STATUS_OFFLINE":     2,
	"AGENT_STATUS_SUSPENDED":   3,
}

func (x AgentStatus) String() string {
	return proto.EnumName(AgentStatus_name, int32(x))
}

func (AgentStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_048f2657adbe63a6, []int{0}
}

type Agent struct {
	Address              string      `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	AgentId              string      `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Capabilities         []string    `protobuf:"bytes,3,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	Model                string      `protobuf:"bytes,4,opt,name=model,proto3" json:"model,omitempty"`
	Reputation           uint64      `protobuf:"varint,5,opt,name=reputation,proto3" json:"reputation,omitempty"`
	Status               AgentStatus `protobuf:"varint,6,opt,name=status,proto3,enum=axon.agent.v1.AgentStatus" json:"status,omitempty"`
	StakeAmount          types.Coin  `protobuf:"bytes,7,opt,name=stake_amount,json=stakeAmount,proto3" json:"stake_amount"`
	RegisteredAt         int64       `protobuf:"varint,8,opt,name=registered_at,json=registeredAt,proto3" json:"registered_at,omitempty"`
	LastHeartbeat        int64       `protobuf:"varint,9,opt,name=last_heartbeat,json=lastHeartbeat,proto3" json:"last_heartbeat,omitempty"`
	BurnedAtRegister     types.Coin  `protobuf:"bytes,10,opt,name=burned_at_register,json=burnedAtRegister,proto3" json:"burned_at_register"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Agent) Reset()         { *m = Agent{} }
func (m *Agent) String() string { return proto.CompactTextString(m) }
func (*Agent) ProtoMessage()    {}
func (*Agent) Descriptor() ([]byte, []int) {
	return fileDescriptor_048f2657adbe63a6, []int{0}
}
func (m *Agent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Agent.Unmarshal(m, b)
}
func (m *Agent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Agent.Marshal(b, m, deterministic)
}
func (m *Agent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Agent.Merge(m, src)
}
func (m *Agent) XXX_Size() int {
	return xxx_messageInfo_Agent.Size(m)
}
func (m *Agent) XXX_DiscardUnknown() {
	xxx_messageInfo_Agent.DiscardUnknown(m)
}

var xxx_messageInfo_Agent proto.InternalMessageInfo

func (m *Agent) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Agent) GetAgentId() string {
	if m != nil {
		return m.AgentId
	}
	return ""
}

func (m *Agent) GetCapabilities() []string {
	if m != nil {
		return m.Capabilities
	}
	return nil
}

func (m *Agent) GetModel() string {
	if m != nil {
		return m.Model
	}
	return ""
}

func (m *Agent) GetReputation() uint64 {
	if m != nil {
		return m.Reputation
	}
	return 0
}

func (m *Agent) GetStatus() AgentStatus {
	if m != nil {
		return m.Status
	}
	return AgentStatus_AGENT_STATUS_UNSPECIFIED
}

func (m *Agent) GetStakeAmount() types.Coin {
	if m != nil {
		return m.StakeAmount
	}
	return types.Coin{}
}

func (m *Agent) GetRegisteredAt() int64 {
	if m != nil {
		return m.RegisteredAt
	}
	return 0
}

func (m *Agent) GetLastHeartbeat() int64 {
	if m != nil {
		return m.LastHeartbeat
	}
	return 0
}

func (m *Agent) GetBurnedAtRegister() types.Coin {
	if m != nil {
		return m.BurnedAtRegister
	}
	return types.Coin{}
}

type AIChallenge struct {
	Epoch                uint64   `protobuf:"varint,1,opt,name=epoch,proto3" json:"epoch,omitempty"`
	ChallengeHash        string   `protobuf:"bytes,2,opt,name=challenge_hash,json=challengeHash,proto3" json:"challenge_hash,omitempty"`
	ChallengeType        string   `protobuf:"bytes,3,opt,name=challenge_type,json=challengeType,proto3" json:"challenge_type,omitempty"`
	ChallengeData        string   `protobuf:"bytes,4,opt,name=challenge_data,json=challengeData,proto3" json:"challenge_data,omitempty"`
	DeadlineBlock        int64    `protobuf:"varint,5,opt,name=deadline_block,json=deadlineBlock,proto3" json:"deadline_block,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AIChallenge) Reset()         { *m = AIChallenge{} }
func (m *AIChallenge) String() string { return proto.CompactTextString(m) }
func (*AIChallenge) ProtoMessage()    {}
func (*AIChallenge) Descriptor() ([]byte, []int) {
	return fileDescriptor_048f2657adbe63a6, []int{1}
}
func (m *AIChallenge) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AIChallenge.Unmarshal(m, b)
}
func (m *AIChallenge) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AIChallenge.Marshal(b, m, deterministic)
}
func (m *AIChallenge) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AIChallenge.Merge(m, src)
}
func (m *AIChallenge) XXX_Size() int {
	return xxx_messageInfo_AIChallenge.Size(m)
}
func (m *AIChallenge) XXX_DiscardUnknown() {
	xxx_messageInfo_AIChallenge.DiscardUnknown(m)
}

var xxx_messageInfo_AIChallenge proto.InternalMessageInfo

func (m *AIChallenge) GetEpoch() uint64 {
	if m != nil {
		return m.Epoch
	}
	return 0
}

func (m *AIChallenge) GetChallengeHash() string {
	if m != nil {
		return m.ChallengeHash
	}
	return ""
}

func (m *AIChallenge) GetChallengeType() string {
	if m != nil {
		return m.ChallengeType
	}
	return ""
}

func (m *AIChallenge) GetChallengeData() string {
	if m != nil {
		return m.ChallengeData
	}
	return ""
}

func (m *AIChallenge) GetDeadlineBlock() int64 {
	if m != nil {
		return m.DeadlineBlock
	}
	return 0
}

type AIResponse struct {
	ValidatorAddress     string   `protobuf:"bytes,1,opt,name=validator_address,json=validatorAddress,proto3" json:"validator_address,omitempty"`
	Epoch                uint64   `protobuf:"varint,2,opt,name=epoch,proto3" json:"epoch,omitempty"`
	CommitHash           string   `protobuf:"bytes,3,opt,name=commit_hash,json=commitHash,proto3" json:"commit_hash,omitempty"`
	RevealData           string   `protobuf:"bytes,4,opt,name=reveal_data,json=revealData,proto3" json:"reveal_data,omitempty"`
	Score                int64    `protobuf:"varint,5,opt,name=score,proto3" json:"score,omitempty"`
	Evaluated            bool     `protobuf:"varint,6,opt,name=evaluated,proto3" json:"evaluated,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AIResponse) Reset()         { *m = AIResponse{} }
func (m *AIResponse) String() string { return proto.CompactTextString(m) }
func (*AIResponse) ProtoMessage()    {}
func (*AIResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_048f2657adbe63a6, []int{2}
}
func (m *AIResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AIResponse.Unmarshal(m, b)
}
func (m *AIResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AIResponse.Marshal(b, m, deterministic)
}
func (m *AIResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AIResponse.Merge(m, src)
}
func (m *AIResponse) XXX_Size() int {
	return xxx_messageInfo_AIResponse.Size(m)
}
func (m *AIResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AIResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AIResponse proto.InternalMessageInfo

func (m *AIResponse) GetValidatorAddress() string {
	if m != nil {
		return m.ValidatorAddress
	}
	return ""
}

func (m *AIResponse) GetEpoch() uint64 {
	if m != nil {
		return m.Epoch
	}
	return 0
}

func (m *AIResponse) GetCommitHash() string {
	if m != nil {
		return m.CommitHash
	}
	return ""
}

func (m *AIResponse) GetRevealData() string {
	if m != nil {
		return m.RevealData
	}
	return ""
}

func (m *AIResponse) GetScore() int64 {
	if m != nil {
		return m.Score
	}
	return 0
}

func (m *AIResponse) GetEvaluated() bool {
	if m != nil {
		return m.Evaluated
	}
	return false
}

func init() {
	proto.RegisterEnum("axon.agent.v1.AgentStatus", AgentStatus_name, AgentStatus_value)
	proto.RegisterType((*Agent)(nil), "axon.agent.v1.Agent")
	proto.RegisterType((*AIChallenge)(nil), "axon.agent.v1.AIChallenge")
	proto.RegisterType((*AIResponse)(nil), "axon.agent.v1.AIResponse")
}

func init() { proto.RegisterFile("axon/agent/v1/agent.proto", fileDescriptor_048f2657adbe63a6) }

var fileDescriptor_048f2657adbe63a6 = []byte{
	// 624 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0x5d, 0x6e, 0xda, 0x40,
	0x10, 0x8e, 0x63, 0x48, 0xc2, 0x10, 0x22, 0xba, 0x45, 0xed, 0x06, 0x45, 0x09, 0xa2, 0xaa, 0x64,
	0xa5, 0xaa, 0x2d, 0xd2, 0x13, 0x98, 0x40, 0x1a, 0xa4, 0x96, 0x46, 0x86, 0xbc, 0xf4, 0xc5, 0x1a,
	0xdb, 0x2b, 0x6c, 0xc5, 0x78, 0x2d, 0xef, 0x82, 0x92, 0xde, 0xa8, 0xa7, 0xe8, 0x53, 0xa5, 0x9e,
	0xa2, 0x67, 0xa9, 0xbc, 0x36, 0x01, 0xe7, 0xa9, 0x6f, 0x33, 0xdf, 0xf7, 0xcd, 0x78, 0xfe, 0xd6,
	0x70, 0x8a, 0x8f, 0x3c, 0xb1, 0x70, 0xc1, 0x12, 0x69, 0xad, 0x07, 0x85, 0x61, 0xa6, 0x19, 0x97,
	0x9c, 0xb4, 0x72, 0xca, 0x2c, 0x90, 0xf5, 0xa0, 0x7b, 0xee, 0x73, 0xb1, 0xe4, 0xc2, 0xf2, 0x50,
	0x30, 0x6b, 0x3d, 0xf0, 0x98, 0xc4, 0x81, 0xe5, 0xf3, 0x28, 0x29, 0xe4, 0xdd, 0xce, 0x82, 0x2f,
	0xb8, 0x32, 0xad, 0xdc, 0x2a, 0xd0, 0xfe, 0x4f, 0x1d, 0xea, 0x76, 0x9e, 0x82, 0x50, 0x38, 0xc4,
	0x20, 0xc8, 0x98, 0x10, 0x54, 0xeb, 0x69, 0x46, 0xc3, 0xd9, 0xb8, 0xe4, 0x14, 0x8e, 0xd4, 0x57,
	0xdc, 0x28, 0xa0, 0xfb, 0x25, 0x95, 0xfb, 0x93, 0x80, 0xf4, 0xe1, 0xd8, 0xc7, 0x14, 0xbd, 0x28,
	0x8e, 0x64, 0xc4, 0x04, 0xd5, 0x7b, 0xba, 0xd1, 0x70, 0x2a, 0x18, 0xe9, 0x40, 0x7d, 0xc9, 0x03,
	0x16, 0xd3, 0x9a, 0x8a, 0x2d, 0x1c, 0x72, 0x0e, 0x90, 0xb1, 0x74, 0x25, 0x51, 0x46, 0x3c, 0xa1,
	0xf5, 0x9e, 0x66, 0xd4, 0x9c, 0x1d, 0x84, 0x5c, 0xc1, 0x81, 0x90, 0x28, 0x57, 0x82, 0x1e, 0xf4,
	0x34, 0xe3, 0xe4, 0xaa, 0x6b, 0x56, 0xda, 0x35, 0x55, 0xd1, 0x33, 0xa5, 0x70, 0x4a, 0x25, 0x19,
	0xc2, 0xb1, 0x90, 0xf8, 0xc0, 0x5c, 0x5c, 0xf2, 0x55, 0x22, 0xe9, 0x61, 0x4f, 0x33, 0x9a, 0x57,
	0xa7, 0x66, 0x31, 0x19, 0x33, 0x9f, 0x8c, 0x59, 0x4e, 0xc6, 0xbc, 0xe6, 0x51, 0x32, 0xac, 0xfd,
	0xf9, 0x7b, 0xb1, 0xe7, 0x34, 0x55, 0x90, 0xad, 0x62, 0xc8, 0x3b, 0x68, 0x65, 0x6c, 0x11, 0x09,
	0xc9, 0x32, 0x16, 0xb8, 0x28, 0xe9, 0x51, 0x4f, 0x33, 0x74, 0xe7, 0x78, 0x0b, 0xda, 0x92, 0xbc,
	0x87, 0x93, 0x18, 0x85, 0x74, 0x43, 0x86, 0x99, 0xf4, 0x18, 0x4a, 0xda, 0x50, 0xaa, 0x56, 0x8e,
	0xde, 0x6e, 0x40, 0xf2, 0x15, 0x88, 0xb7, 0xca, 0x12, 0x95, 0xc7, 0xdd, 0x24, 0xa0, 0xf0, 0x7f,
	0x55, 0xb5, 0x8b, 0x50, 0x5b, 0x3a, 0x65, 0x60, 0xff, 0x97, 0x06, 0x4d, 0x7b, 0x72, 0x1d, 0x62,
	0x1c, 0xb3, 0x64, 0xc1, 0xf2, 0xc1, 0xb2, 0x94, 0xfb, 0xa1, 0xda, 0x57, 0xcd, 0x29, 0x9c, 0xbc,
	0x36, 0x7f, 0x23, 0x71, 0x43, 0x14, 0x61, 0xb9, 0xb3, 0xd6, 0x33, 0x7a, 0x8b, 0xe2, 0x85, 0x4c,
	0x3e, 0xa5, 0x8c, 0xea, 0x2f, 0x64, 0xf3, 0xa7, 0x94, 0x55, 0x65, 0x01, 0x4a, 0x2c, 0xb7, 0xb8,
	0x95, 0x8d, 0x50, 0x62, 0x2e, 0x0b, 0x18, 0x06, 0x71, 0x94, 0x30, 0xd7, 0x8b, 0xb9, 0xff, 0xa0,
	0x36, 0xaa, 0x3b, 0xad, 0x0d, 0x3a, 0xcc, 0xc1, 0xfe, 0x6f, 0x0d, 0xc0, 0x9e, 0x38, 0x4c, 0xa4,
	0x3c, 0x11, 0x8c, 0x7c, 0x80, 0x57, 0x6b, 0x8c, 0xa3, 0x00, 0x25, 0xcf, 0xdc, 0xea, 0xf1, 0xb5,
	0x9f, 0x09, 0xbb, 0xbc, 0xc2, 0xe7, 0x6e, 0xf7, 0x77, 0xbb, 0xbd, 0x80, 0xa6, 0xcf, 0x97, 0xcb,
	0x48, 0x16, 0xad, 0x16, 0x3d, 0x40, 0x01, 0xa9, 0x3e, 0x2f, 0xa0, 0x99, 0xb1, 0x35, 0xc3, 0x78,
	0xb7, 0x7a, 0x28, 0x20, 0x55, 0x7a, 0x07, 0xea, 0xc2, 0xe7, 0x19, 0x2b, 0x2b, 0x2e, 0x1c, 0x72,
	0x06, 0x0d, 0xb6, 0xc6, 0x78, 0x85, 0x92, 0x05, 0xea, 0x02, 0x8f, 0x9c, 0x2d, 0x70, 0xf9, 0x03,
	0x9a, 0x3b, 0xf7, 0x47, 0xce, 0x80, 0xda, 0x9f, 0xc7, 0xd3, 0xb9, 0x3b, 0x9b, 0xdb, 0xf3, 0xfb,
	0x99, 0x7b, 0x3f, 0x9d, 0xdd, 0x8d, 0xaf, 0x27, 0x37, 0x93, 0xf1, 0xa8, 0xbd, 0x47, 0xde, 0xc2,
	0xeb, 0x0a, 0xfb, 0x6d, 0xfa, 0x65, 0x32, 0x1d, 0xb7, 0x35, 0x42, 0xa1, 0x53, 0x25, 0x6e, 0x6e,
	0x14, 0xb3, 0x4f, 0xba, 0xf0, 0xa6, 0xc2, 0xcc, 0xee, 0x67, 0x77, 0xe3, 0xe9, 0x68, 0x3c, 0x6a,
	0xeb, 0xc3, 0xcb, 0xef, 0xc6, 0x22, 0x92, 0xe1, 0xca, 0x33, 0x7d, 0xbe, 0xb4, 0xf2, 0x47, 0xf1,
	0xd1, 0x0f, 0x31, 0x4a, 0x94, 0x69, 0x3d, 0x96, 0xff, 0x8a, 0x7c, 0xa3, 0xc2, 0x3b, 0x50, 0x8f,
	0xfc, 0xd3, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x0f, 0xdf, 0x53, 0x73, 0x46, 0x04, 0x00, 0x00,
}
