package types

import "cosmossdk.io/errors"

var (
	ErrAgentAlreadyRegistered     = errors.Register(ModuleName, 1100, "agent already registered")
	ErrAgentNotFound              = errors.Register(ModuleName, 1101, "agent not found")
	ErrInsufficientStake          = errors.Register(ModuleName, 1102, "insufficient stake amount")
	ErrAgentSuspended             = errors.Register(ModuleName, 1103, "agent is suspended")
	ErrHeartbeatTooFrequent       = errors.Register(ModuleName, 1104, "heartbeat sent too frequently")
	ErrChallengeNotActive         = errors.Register(ModuleName, 1105, "no active AI challenge")
	ErrChallengeExpired           = errors.Register(ModuleName, 1106, "AI challenge submission window expired")
	ErrAlreadySubmitted           = errors.Register(ModuleName, 1107, "already submitted response for this epoch")
	ErrInvalidReveal              = errors.Register(ModuleName, 1108, "reveal does not match commit hash")
	ErrReputationTooLow           = errors.Register(ModuleName, 1109, "reputation below minimum threshold")
	ErrDeregisterCooldown         = errors.Register(ModuleName, 1110, "agent in deregister cooldown period")
	ErrDeregisterAlreadyQueued    = errors.Register(ModuleName, 1111, "deregister already requested")
	ErrChallengeWindowClosed      = errors.Register(ModuleName, 1112, "challenge submission window closed")
	ErrAgentOffline               = errors.Register(ModuleName, 1113, "agent is offline")
	ErrRevealTooEarly             = errors.Register(ModuleName, 1114, "reveal phase has not started yet")
	ErrRevealWindowClosed         = errors.Register(ModuleName, 1115, "reveal window has closed")
	ErrAlreadyEvaluated           = errors.Register(ModuleName, 1116, "challenge already evaluated")
	ErrDailyRegisterLimitExceeded = errors.Register(ModuleName, 1117, "daily registration limit exceeded (max 3 per address per day)")
	ErrInvalidStakeDenom          = errors.Register(ModuleName, 1118, "invalid stake denom")
	ErrStakeAmountMustBePositive  = errors.Register(ModuleName, 1119, "stake amount must be positive")
	ErrValidatorRequired          = errors.Register(ModuleName, 1120, "operation requires an active bonded validator")
	ErrBelowMinimumStake          = errors.Register(ModuleName, 1121, "stake would fall below minimum registration stake")
	ErrPendingReduceExists        = errors.Register(ModuleName, 1122, "a pending stake reduction already exists")
	ErrNoReducePending            = errors.Register(ModuleName, 1123, "no pending stake reduction to claim")
	ErrReduceNotUnlocked          = errors.Register(ModuleName, 1124, "pending stake reduction has not reached unlock height")

	ErrServiceNotFound           = errors.Register(ModuleName, 1130, "service not found")
	ErrServiceAlreadyExists     = errors.Register(ModuleName, 1131, "service with this name already exists")
	ErrServiceNotActive         = errors.Register(ModuleName, 1132, "service is not active")
	ErrServiceNameInvalid      = errors.Register(ModuleName, 1133, "invalid service name")
	ErrUnauthorized           = errors.Register(ModuleName, 1134, "unauthorized")

	ErrTaskNotFound            = errors.Register(ModuleName, 1140, "task not found")
	ErrTaskNotOpen           = errors.Register(ModuleName, 1141, "task is not open for bidding")
	ErrTaskExpired            = errors.Register(ModuleName, 1142, "task deadline passed")
	ErrTaskAlreadyCompleted  = errors.Register(ModuleName, 1143, "task already completed")
	ErrBidAlreadyExists     = errors.Register(ModuleName, 1144, "bid already submitted")
	ErrBidTooLate            = errors.Register(ModuleName, 1145, "bidding deadline passed")
	ErrInsufficientBudget   = errors.Register(ModuleName, 1146, "bid price exceeds budget")

	ErrToolNotFound          = errors.Register(ModuleName, 1150, "tool not found")
	ErrToolNotActive         = errors.Register(ModuleName, 1151, "tool is not active")
	ErrToolNotPublic         = errors.Register(ModuleName, 1152, "tool is not public")
	ErrToolCallFailed       = errors.Register(ModuleName, 1153, "tool call failed")
	ErrInvalidToolInput    = errors.Register(ModuleName, 1154, "invalid tool input")
)
