// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: axon/agent/v1/query.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type QueryParamsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_76d159402b89041f, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryParamsRequest.Unmarshal(m, b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return xxx_messageInfo_QueryParamsRequest.Size(m)
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

type QueryParamsResponse struct {
	Params               Params   `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_76d159402b89041f, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryParamsResponse.Unmarshal(m, b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return xxx_messageInfo_QueryParamsResponse.Size(m)
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

type QueryAgentRequest struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryAgentRequest) Reset()         { *m = QueryAgentRequest{} }
func (m *QueryAgentRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAgentRequest) ProtoMessage()    {}
func (*QueryAgentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_76d159402b89041f, []int{2}
}
func (m *QueryAgentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryAgentRequest.Unmarshal(m, b)
}
func (m *QueryAgentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryAgentRequest.Marshal(b, m, deterministic)
}
func (m *QueryAgentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAgentRequest.Merge(m, src)
}
func (m *QueryAgentRequest) XXX_Size() int {
	return xxx_messageInfo_QueryAgentRequest.Size(m)
}
func (m *QueryAgentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAgentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAgentRequest proto.InternalMessageInfo

func (m *QueryAgentRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type QueryAgentResponse struct {
	Agent                *Agent   `protobuf:"bytes,1,opt,name=agent,proto3" json:"agent,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryAgentResponse) Reset()         { *m = QueryAgentResponse{} }
func (m *QueryAgentResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAgentResponse) ProtoMessage()    {}
func (*QueryAgentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_76d159402b89041f, []int{3}
}
func (m *QueryAgentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryAgentResponse.Unmarshal(m, b)
}
func (m *QueryAgentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryAgentResponse.Marshal(b, m, deterministic)
}
func (m *QueryAgentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAgentResponse.Merge(m, src)
}
func (m *QueryAgentResponse) XXX_Size() int {
	return xxx_messageInfo_QueryAgentResponse.Size(m)
}
func (m *QueryAgentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAgentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAgentResponse proto.InternalMessageInfo

func (m *QueryAgentResponse) GetAgent() *Agent {
	if m != nil {
		return m.Agent
	}
	return nil
}

type QueryAgentsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryAgentsRequest) Reset()         { *m = QueryAgentsRequest{} }
func (m *QueryAgentsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAgentsRequest) ProtoMessage()    {}
func (*QueryAgentsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_76d159402b89041f, []int{4}
}
func (m *QueryAgentsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryAgentsRequest.Unmarshal(m, b)
}
func (m *QueryAgentsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryAgentsRequest.Marshal(b, m, deterministic)
}
func (m *QueryAgentsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAgentsRequest.Merge(m, src)
}
func (m *QueryAgentsRequest) XXX_Size() int {
	return xxx_messageInfo_QueryAgentsRequest.Size(m)
}
func (m *QueryAgentsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAgentsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAgentsRequest proto.InternalMessageInfo

type QueryAgentsResponse struct {
	Agents               []Agent  `protobuf:"bytes,1,rep,name=agents,proto3" json:"agents"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryAgentsResponse) Reset()         { *m = QueryAgentsResponse{} }
func (m *QueryAgentsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAgentsResponse) ProtoMessage()    {}
func (*QueryAgentsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_76d159402b89041f, []int{5}
}
func (m *QueryAgentsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryAgentsResponse.Unmarshal(m, b)
}
func (m *QueryAgentsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryAgentsResponse.Marshal(b, m, deterministic)
}
func (m *QueryAgentsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAgentsResponse.Merge(m, src)
}
func (m *QueryAgentsResponse) XXX_Size() int {
	return xxx_messageInfo_QueryAgentsResponse.Size(m)
}
func (m *QueryAgentsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAgentsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAgentsResponse proto.InternalMessageInfo

func (m *QueryAgentsResponse) GetAgents() []Agent {
	if m != nil {
		return m.Agents
	}
	return nil
}

type QueryReputationRequest struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryReputationRequest) Reset()         { *m = QueryReputationRequest{} }
func (m *QueryReputationRequest) String() string { return proto.CompactTextString(m) }
func (*QueryReputationRequest) ProtoMessage()    {}
func (*QueryReputationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_76d159402b89041f, []int{6}
}
func (m *QueryReputationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryReputationRequest.Unmarshal(m, b)
}
func (m *QueryReputationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryReputationRequest.Marshal(b, m, deterministic)
}
func (m *QueryReputationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryReputationRequest.Merge(m, src)
}
func (m *QueryReputationRequest) XXX_Size() int {
	return xxx_messageInfo_QueryReputationRequest.Size(m)
}
func (m *QueryReputationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryReputationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryReputationRequest proto.InternalMessageInfo

func (m *QueryReputationRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type QueryReputationResponse struct {
	Reputation           uint64   `protobuf:"varint,1,opt,name=reputation,proto3" json:"reputation,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryReputationResponse) Reset()         { *m = QueryReputationResponse{} }
func (m *QueryReputationResponse) String() string { return proto.CompactTextString(m) }
func (*QueryReputationResponse) ProtoMessage()    {}
func (*QueryReputationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_76d159402b89041f, []int{7}
}
func (m *QueryReputationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryReputationResponse.Unmarshal(m, b)
}
func (m *QueryReputationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryReputationResponse.Marshal(b, m, deterministic)
}
func (m *QueryReputationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryReputationResponse.Merge(m, src)
}
func (m *QueryReputationResponse) XXX_Size() int {
	return xxx_messageInfo_QueryReputationResponse.Size(m)
}
func (m *QueryReputationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryReputationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryReputationResponse proto.InternalMessageInfo

func (m *QueryReputationResponse) GetReputation() uint64 {
	if m != nil {
		return m.Reputation
	}
	return 0
}

type QueryCurrentChallengeRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryCurrentChallengeRequest) Reset()         { *m = QueryCurrentChallengeRequest{} }
func (m *QueryCurrentChallengeRequest) String() string { return proto.CompactTextString(m) }
func (*QueryCurrentChallengeRequest) ProtoMessage()    {}
func (*QueryCurrentChallengeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_76d159402b89041f, []int{8}
}
func (m *QueryCurrentChallengeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryCurrentChallengeRequest.Unmarshal(m, b)
}
func (m *QueryCurrentChallengeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryCurrentChallengeRequest.Marshal(b, m, deterministic)
}
func (m *QueryCurrentChallengeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryCurrentChallengeRequest.Merge(m, src)
}
func (m *QueryCurrentChallengeRequest) XXX_Size() int {
	return xxx_messageInfo_QueryCurrentChallengeRequest.Size(m)
}
func (m *QueryCurrentChallengeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryCurrentChallengeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryCurrentChallengeRequest proto.InternalMessageInfo

type QueryCurrentChallengeResponse struct {
	Challenge            *AIChallenge `protobuf:"bytes,1,opt,name=challenge,proto3" json:"challenge,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *QueryCurrentChallengeResponse) Reset()         { *m = QueryCurrentChallengeResponse{} }
func (m *QueryCurrentChallengeResponse) String() string { return proto.CompactTextString(m) }
func (*QueryCurrentChallengeResponse) ProtoMessage()    {}
func (*QueryCurrentChallengeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_76d159402b89041f, []int{9}
}
func (m *QueryCurrentChallengeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryCurrentChallengeResponse.Unmarshal(m, b)
}
func (m *QueryCurrentChallengeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryCurrentChallengeResponse.Marshal(b, m, deterministic)
}
func (m *QueryCurrentChallengeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryCurrentChallengeResponse.Merge(m, src)
}
func (m *QueryCurrentChallengeResponse) XXX_Size() int {
	return xxx_messageInfo_QueryCurrentChallengeResponse.Size(m)
}
func (m *QueryCurrentChallengeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryCurrentChallengeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryCurrentChallengeResponse proto.InternalMessageInfo

func (m *QueryCurrentChallengeResponse) GetChallenge() *AIChallenge {
	if m != nil {
		return m.Challenge
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "axon.agent.v1.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "axon.agent.v1.QueryParamsResponse")
	proto.RegisterType((*QueryAgentRequest)(nil), "axon.agent.v1.QueryAgentRequest")
	proto.RegisterType((*QueryAgentResponse)(nil), "axon.agent.v1.QueryAgentResponse")
	proto.RegisterType((*QueryAgentsRequest)(nil), "axon.agent.v1.QueryAgentsRequest")
	proto.RegisterType((*QueryAgentsResponse)(nil), "axon.agent.v1.QueryAgentsResponse")
	proto.RegisterType((*QueryReputationRequest)(nil), "axon.agent.v1.QueryReputationRequest")
	proto.RegisterType((*QueryReputationResponse)(nil), "axon.agent.v1.QueryReputationResponse")
	proto.RegisterType((*QueryCurrentChallengeRequest)(nil), "axon.agent.v1.QueryCurrentChallengeRequest")
	proto.RegisterType((*QueryCurrentChallengeResponse)(nil), "axon.agent.v1.QueryCurrentChallengeResponse")
}

func init() { proto.RegisterFile("axon/agent/v1/query.proto", fileDescriptor_76d159402b89041f) }

var fileDescriptor_76d159402b89041f = []byte{
	// 511 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0xbf, 0x6f, 0xd3, 0x40,
	0x14, 0x26, 0xd0, 0x04, 0xf5, 0x21, 0x24, 0x38, 0x52, 0x5a, 0x4e, 0x6d, 0x48, 0x0f, 0xb5, 0x8a,
	0x5a, 0xea, 0x53, 0xd3, 0x05, 0x36, 0x68, 0xa7, 0x32, 0x81, 0x37, 0xd8, 0xae, 0xe9, 0xc9, 0x89,
	0x94, 0xde, 0xb9, 0xf6, 0xb9, 0x6a, 0x85, 0x58, 0x3a, 0xb1, 0x33, 0xf0, 0x2f, 0xb1, 0xb3, 0x33,
	0xf1, 0x87, 0x20, 0xbf, 0x77, 0xce, 0x0f, 0xc7, 0x4e, 0xd9, 0x9c, 0x77, 0xdf, 0x8f, 0xf7, 0xf9,
	0xbe, 0x18, 0x5e, 0xa8, 0x6b, 0x6b, 0xa4, 0x8a, 0xb4, 0x71, 0xf2, 0xea, 0x50, 0x5e, 0x66, 0x3a,
	0xb9, 0x09, 0xe2, 0xc4, 0x3a, 0xcb, 0x1e, 0xe7, 0x47, 0x01, 0x1e, 0x05, 0x57, 0x87, 0x7c, 0x33,
	0xb2, 0x36, 0x1a, 0x6b, 0xa9, 0xe2, 0x91, 0x54, 0xc6, 0x58, 0xa7, 0xdc, 0xc8, 0x9a, 0x94, 0xc0,
	0xbc, 0xa4, 0x43, 0x2c, 0x3a, 0xe2, 0xf3, 0x47, 0xb1, 0x4a, 0xd4, 0x45, 0x41, 0x6b, 0x47, 0x36,
	0xb2, 0xf8, 0x28, 0xf3, 0x27, 0x9a, 0x8a, 0x36, 0xb0, 0x4f, 0xf9, 0x22, 0x1f, 0x11, 0x1a, 0xea,
	0xcb, 0x4c, 0xa7, 0x4e, 0x7c, 0x80, 0x67, 0x73, 0xd3, 0x34, 0xb6, 0x26, 0xd5, 0xec, 0x08, 0x5a,
	0x24, 0xb9, 0xd1, 0xe8, 0x36, 0x7a, 0x8f, 0xfa, 0x6b, 0xc1, 0xdc, 0xde, 0x01, 0xc1, 0x8f, 0x57,
	0x7e, 0xfd, 0x79, 0x79, 0x2f, 0xf4, 0x50, 0x71, 0x00, 0x4f, 0x51, 0xeb, 0x7d, 0x8e, 0xf2, 0x06,
	0x6c, 0x03, 0x1e, 0xaa, 0xf3, 0xf3, 0x44, 0xa7, 0x24, 0xb5, 0x1a, 0x16, 0x3f, 0xc5, 0x3b, 0xbf,
	0x90, 0x87, 0x7b, 0xe7, 0x3d, 0x68, 0xa2, 0x8b, 0x37, 0x6e, 0x97, 0x8c, 0x09, 0x4c, 0x90, 0x49,
	0x24, 0x1c, 0x4e, 0x22, 0x9d, 0xfa, 0x48, 0xc5, 0xd4, 0x0b, 0xf7, 0xa1, 0x85, 0xac, 0x7c, 0x8f,
	0x07, 0x75, 0xca, 0x45, 0x22, 0x42, 0x8a, 0x3e, 0x3c, 0x47, 0xa9, 0x50, 0xc7, 0x19, 0x5d, 0xcd,
	0xdd, 0xb1, 0xde, 0xc2, 0xfa, 0x02, 0xc7, 0xaf, 0xd0, 0x01, 0x48, 0x26, 0x53, 0xe4, 0xad, 0x84,
	0x33, 0x13, 0xd1, 0x81, 0x4d, 0xa4, 0x9e, 0x64, 0x49, 0xa2, 0x8d, 0x3b, 0x19, 0xaa, 0xf1, 0x58,
	0x9b, 0x48, 0x17, 0xc9, 0x3e, 0xc3, 0x56, 0xcd, 0xb9, 0x37, 0x78, 0x03, 0xab, 0x83, 0x62, 0xe8,
	0x5f, 0x20, 0x2f, 0xc7, 0x3c, 0x9d, 0xd2, 0xa6, 0xe0, 0xfe, 0x6d, 0x13, 0x9a, 0xa8, 0xcd, 0x0c,
	0xb4, 0xe8, 0x76, 0xd9, 0x76, 0x89, 0xba, 0x58, 0x1f, 0x2e, 0x96, 0x41, 0x68, 0x29, 0xb1, 0x75,
	0xfb, 0xfb, 0xef, 0x8f, 0xfb, 0xeb, 0x6c, 0x4d, 0x56, 0x75, 0x96, 0x39, 0x68, 0xe2, 0xab, 0x67,
	0xdd, 0x2a, 0xad, 0xd9, 0x2e, 0xf1, 0xed, 0x25, 0x08, 0x6f, 0xb6, 0x8b, 0x66, 0x5d, 0xd6, 0x91,
	0x15, 0xff, 0x1d, 0xf9, 0xd5, 0x5f, 0xd2, 0xb7, 0x3c, 0x25, 0xf5, 0x83, 0xd5, 0x8b, 0x2e, 0x4f,
	0x39, 0x5f, 0xaf, 0xda, 0x94, 0xd4, 0x24, 0xf6, 0xbd, 0x01, 0x30, 0x6d, 0x04, 0xdb, 0xa9, 0x52,
	0x5c, 0x68, 0x19, 0xdf, 0xbd, 0x0b, 0xe6, 0xcd, 0xf7, 0xd1, 0x7c, 0x87, 0xbd, 0x2a, 0x99, 0x4f,
	0xbb, 0x35, 0x13, 0xfd, 0x67, 0x03, 0x9e, 0x94, 0x1b, 0xc4, 0xf6, 0xab, 0x9c, 0x6a, 0x7a, 0xc8,
	0x5f, 0xff, 0x1f, 0xd8, 0x2f, 0xd7, 0xc3, 0xe5, 0x04, 0xeb, 0x96, 0x96, 0x9b, 0x94, 0x4f, 0x0e,
	0x88, 0x7a, 0xbc, 0xf7, 0xa5, 0x17, 0x8d, 0xdc, 0x30, 0x3b, 0x0b, 0x06, 0xf6, 0x02, 0xd1, 0x07,
	0x83, 0xa1, 0x1a, 0x19, 0x22, 0x5e, 0x7b, 0xaa, 0xbb, 0x89, 0x75, 0x7a, 0xd6, 0xc2, 0xaf, 0xda,
	0xd1, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xce, 0xab, 0xd8, 0xc2, 0x6c, 0x05, 0x00, 0x00,
}
