// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: axon/agent/v1/tx.proto

package types

import (
	fmt "fmt"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgRegister struct {
	Sender               string     `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	Capabilities         string     `protobuf:"bytes,2,opt,name=capabilities,proto3" json:"capabilities,omitempty"`
	Model                string     `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	Stake                types.Coin `protobuf:"bytes,4,opt,name=stake,proto3" json:"stake"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *MsgRegister) Reset()         { *m = MsgRegister{} }
func (m *MsgRegister) String() string { return proto.CompactTextString(m) }
func (*MsgRegister) ProtoMessage()    {}
func (*MsgRegister) Descriptor() ([]byte, []int) {
	return fileDescriptor_b77bc60185085f37, []int{0}
}
func (m *MsgRegister) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgRegister.Unmarshal(m, b)
}
func (m *MsgRegister) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgRegister.Marshal(b, m, deterministic)
}
func (m *MsgRegister) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRegister.Merge(m, src)
}
func (m *MsgRegister) XXX_Size() int {
	return xxx_messageInfo_MsgRegister.Size(m)
}
func (m *MsgRegister) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRegister.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRegister proto.InternalMessageInfo

func (m *MsgRegister) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

func (m *MsgRegister) GetCapabilities() string {
	if m != nil {
		return m.Capabilities
	}
	return ""
}

func (m *MsgRegister) GetModel() string {
	if m != nil {
		return m.Model
	}
	return ""
}

func (m *MsgRegister) GetStake() types.Coin {
	if m != nil {
		return m.Stake
	}
	return types.Coin{}
}

type MsgRegisterResponse struct {
	AgentId              string   `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgRegisterResponse) Reset()         { *m = MsgRegisterResponse{} }
func (m *MsgRegisterResponse) String() string { return proto.CompactTextString(m) }
func (*MsgRegisterResponse) ProtoMessage()    {}
func (*MsgRegisterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b77bc60185085f37, []int{1}
}
func (m *MsgRegisterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgRegisterResponse.Unmarshal(m, b)
}
func (m *MsgRegisterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgRegisterResponse.Marshal(b, m, deterministic)
}
func (m *MsgRegisterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRegisterResponse.Merge(m, src)
}
func (m *MsgRegisterResponse) XXX_Size() int {
	return xxx_messageInfo_MsgRegisterResponse.Size(m)
}
func (m *MsgRegisterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRegisterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRegisterResponse proto.InternalMessageInfo

func (m *MsgRegisterResponse) GetAgentId() string {
	if m != nil {
		return m.AgentId
	}
	return ""
}

type MsgAddStake struct {
	Sender               string     `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	Stake                types.Coin `protobuf:"bytes,2,opt,name=stake,proto3" json:"stake"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *MsgAddStake) Reset()         { *m = MsgAddStake{} }
func (m *MsgAddStake) String() string { return proto.CompactTextString(m) }
func (*MsgAddStake) ProtoMessage()    {}
func (*MsgAddStake) Descriptor() ([]byte, []int) {
	return fileDescriptor_b77bc60185085f37, []int{2}
}
func (m *MsgAddStake) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgAddStake.Unmarshal(m, b)
}
func (m *MsgAddStake) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgAddStake.Marshal(b, m, deterministic)
}
func (m *MsgAddStake) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgAddStake.Merge(m, src)
}
func (m *MsgAddStake) XXX_Size() int {
	return xxx_messageInfo_MsgAddStake.Size(m)
}
func (m *MsgAddStake) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgAddStake.DiscardUnknown(m)
}

var xxx_messageInfo_MsgAddStake proto.InternalMessageInfo

func (m *MsgAddStake) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

func (m *MsgAddStake) GetStake() types.Coin {
	if m != nil {
		return m.Stake
	}
	return types.Coin{}
}

type MsgAddStakeResponse struct {
	TotalStake           types.Coin `protobuf:"bytes,1,opt,name=total_stake,json=totalStake,proto3" json:"total_stake"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *MsgAddStakeResponse) Reset()         { *m = MsgAddStakeResponse{} }
func (m *MsgAddStakeResponse) String() string { return proto.CompactTextString(m) }
func (*MsgAddStakeResponse) ProtoMessage()    {}
func (*MsgAddStakeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b77bc60185085f37, []int{3}
}
func (m *MsgAddStakeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgAddStakeResponse.Unmarshal(m, b)
}
func (m *MsgAddStakeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgAddStakeResponse.Marshal(b, m, deterministic)
}
func (m *MsgAddStakeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgAddStakeResponse.Merge(m, src)
}
func (m *MsgAddStakeResponse) XXX_Size() int {
	return xxx_messageInfo_MsgAddStakeResponse.Size(m)
}
func (m *MsgAddStakeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgAddStakeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgAddStakeResponse proto.InternalMessageInfo

func (m *MsgAddStakeResponse) GetTotalStake() types.Coin {
	if m != nil {
		return m.TotalStake
	}
	return types.Coin{}
}

type MsgUpdateAgent struct {
	Sender               string   `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	Capabilities         string   `protobuf:"bytes,2,opt,name=capabilities,proto3" json:"capabilities,omitempty"`
	Model                string   `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgUpdateAgent) Reset()         { *m = MsgUpdateAgent{} }
func (m *MsgUpdateAgent) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateAgent) ProtoMessage()    {}
func (*MsgUpdateAgent) Descriptor() ([]byte, []int) {
	return fileDescriptor_b77bc60185085f37, []int{4}
}
func (m *MsgUpdateAgent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgUpdateAgent.Unmarshal(m, b)
}
func (m *MsgUpdateAgent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgUpdateAgent.Marshal(b, m, deterministic)
}
func (m *MsgUpdateAgent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateAgent.Merge(m, src)
}
func (m *MsgUpdateAgent) XXX_Size() int {
	return xxx_messageInfo_MsgUpdateAgent.Size(m)
}
func (m *MsgUpdateAgent) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateAgent.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateAgent proto.InternalMessageInfo

func (m *MsgUpdateAgent) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

func (m *MsgUpdateAgent) GetCapabilities() string {
	if m != nil {
		return m.Capabilities
	}
	return ""
}

func (m *MsgUpdateAgent) GetModel() string {
	if m != nil {
		return m.Model
	}
	return ""
}

type MsgUpdateAgentResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgUpdateAgentResponse) Reset()         { *m = MsgUpdateAgentResponse{} }
func (m *MsgUpdateAgentResponse) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateAgentResponse) ProtoMessage()    {}
func (*MsgUpdateAgentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b77bc60185085f37, []int{5}
}
func (m *MsgUpdateAgentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgUpdateAgentResponse.Unmarshal(m, b)
}
func (m *MsgUpdateAgentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgUpdateAgentResponse.Marshal(b, m, deterministic)
}
func (m *MsgUpdateAgentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateAgentResponse.Merge(m, src)
}
func (m *MsgUpdateAgentResponse) XXX_Size() int {
	return xxx_messageInfo_MsgUpdateAgentResponse.Size(m)
}
func (m *MsgUpdateAgentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateAgentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateAgentResponse proto.InternalMessageInfo

type MsgHeartbeat struct {
	Sender               string   `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgHeartbeat) Reset()         { *m = MsgHeartbeat{} }
func (m *MsgHeartbeat) String() string { return proto.CompactTextString(m) }
func (*MsgHeartbeat) ProtoMessage()    {}
func (*MsgHeartbeat) Descriptor() ([]byte, []int) {
	return fileDescriptor_b77bc60185085f37, []int{6}
}
func (m *MsgHeartbeat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgHeartbeat.Unmarshal(m, b)
}
func (m *MsgHeartbeat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgHeartbeat.Marshal(b, m, deterministic)
}
func (m *MsgHeartbeat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgHeartbeat.Merge(m, src)
}
func (m *MsgHeartbeat) XXX_Size() int {
	return xxx_messageInfo_MsgHeartbeat.Size(m)
}
func (m *MsgHeartbeat) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgHeartbeat.DiscardUnknown(m)
}

var xxx_messageInfo_MsgHeartbeat proto.InternalMessageInfo

func (m *MsgHeartbeat) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

type MsgHeartbeatResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgHeartbeatResponse) Reset()         { *m = MsgHeartbeatResponse{} }
func (m *MsgHeartbeatResponse) String() string { return proto.CompactTextString(m) }
func (*MsgHeartbeatResponse) ProtoMessage()    {}
func (*MsgHeartbeatResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b77bc60185085f37, []int{7}
}
func (m *MsgHeartbeatResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgHeartbeatResponse.Unmarshal(m, b)
}
func (m *MsgHeartbeatResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgHeartbeatResponse.Marshal(b, m, deterministic)
}
func (m *MsgHeartbeatResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgHeartbeatResponse.Merge(m, src)
}
func (m *MsgHeartbeatResponse) XXX_Size() int {
	return xxx_messageInfo_MsgHeartbeatResponse.Size(m)
}
func (m *MsgHeartbeatResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgHeartbeatResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgHeartbeatResponse proto.InternalMessageInfo

type MsgDeregister struct {
	Sender               string   `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgDeregister) Reset()         { *m = MsgDeregister{} }
func (m *MsgDeregister) String() string { return proto.CompactTextString(m) }
func (*MsgDeregister) ProtoMessage()    {}
func (*MsgDeregister) Descriptor() ([]byte, []int) {
	return fileDescriptor_b77bc60185085f37, []int{8}
}
func (m *MsgDeregister) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgDeregister.Unmarshal(m, b)
}
func (m *MsgDeregister) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgDeregister.Marshal(b, m, deterministic)
}
func (m *MsgDeregister) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgDeregister.Merge(m, src)
}
func (m *MsgDeregister) XXX_Size() int {
	return xxx_messageInfo_MsgDeregister.Size(m)
}
func (m *MsgDeregister) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgDeregister.DiscardUnknown(m)
}

var xxx_messageInfo_MsgDeregister proto.InternalMessageInfo

func (m *MsgDeregister) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

type MsgDeregisterResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgDeregisterResponse) Reset()         { *m = MsgDeregisterResponse{} }
func (m *MsgDeregisterResponse) String() string { return proto.CompactTextString(m) }
func (*MsgDeregisterResponse) ProtoMessage()    {}
func (*MsgDeregisterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b77bc60185085f37, []int{9}
}
func (m *MsgDeregisterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgDeregisterResponse.Unmarshal(m, b)
}
func (m *MsgDeregisterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgDeregisterResponse.Marshal(b, m, deterministic)
}
func (m *MsgDeregisterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgDeregisterResponse.Merge(m, src)
}
func (m *MsgDeregisterResponse) XXX_Size() int {
	return xxx_messageInfo_MsgDeregisterResponse.Size(m)
}
func (m *MsgDeregisterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgDeregisterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgDeregisterResponse proto.InternalMessageInfo

type MsgReduceStake struct {
	Sender               string     `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	Amount               types.Coin `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *MsgReduceStake) Reset()         { *m = MsgReduceStake{} }
func (m *MsgReduceStake) String() string { return proto.CompactTextString(m) }
func (*MsgReduceStake) ProtoMessage()    {}
func (*MsgReduceStake) Descriptor() ([]byte, []int) {
	return fileDescriptor_b77bc60185085f37, []int{10}
}
func (m *MsgReduceStake) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgReduceStake.Unmarshal(m, b)
}
func (m *MsgReduceStake) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgReduceStake.Marshal(b, m, deterministic)
}
func (m *MsgReduceStake) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgReduceStake.Merge(m, src)
}
func (m *MsgReduceStake) XXX_Size() int {
	return xxx_messageInfo_MsgReduceStake.Size(m)
}
func (m *MsgReduceStake) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgReduceStake.DiscardUnknown(m)
}

var xxx_messageInfo_MsgReduceStake proto.InternalMessageInfo

func (m *MsgReduceStake) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

func (m *MsgReduceStake) GetAmount() types.Coin {
	if m != nil {
		return m.Amount
	}
	return types.Coin{}
}

type MsgReduceStakeResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgReduceStakeResponse) Reset()         { *m = MsgReduceStakeResponse{} }
func (m *MsgReduceStakeResponse) String() string { return proto.CompactTextString(m) }
func (*MsgReduceStakeResponse) ProtoMessage()    {}
func (*MsgReduceStakeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b77bc60185085f37, []int{11}
}
func (m *MsgReduceStakeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgReduceStakeResponse.Unmarshal(m, b)
}
func (m *MsgReduceStakeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgReduceStakeResponse.Marshal(b, m, deterministic)
}
func (m *MsgReduceStakeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgReduceStakeResponse.Merge(m, src)
}
func (m *MsgReduceStakeResponse) XXX_Size() int {
	return xxx_messageInfo_MsgReduceStakeResponse.Size(m)
}
func (m *MsgReduceStakeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgReduceStakeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgReduceStakeResponse proto.InternalMessageInfo

type MsgClaimReducedStake struct {
	Sender               string   `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgClaimReducedStake) Reset()         { *m = MsgClaimReducedStake{} }
func (m *MsgClaimReducedStake) String() string { return proto.CompactTextString(m) }
func (*MsgClaimReducedStake) ProtoMessage()    {}
func (*MsgClaimReducedStake) Descriptor() ([]byte, []int) {
	return fileDescriptor_b77bc60185085f37, []int{12}
}
func (m *MsgClaimReducedStake) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgClaimReducedStake.Unmarshal(m, b)
}
func (m *MsgClaimReducedStake) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgClaimReducedStake.Marshal(b, m, deterministic)
}
func (m *MsgClaimReducedStake) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgClaimReducedStake.Merge(m, src)
}
func (m *MsgClaimReducedStake) XXX_Size() int {
	return xxx_messageInfo_MsgClaimReducedStake.Size(m)
}
func (m *MsgClaimReducedStake) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgClaimReducedStake.DiscardUnknown(m)
}

var xxx_messageInfo_MsgClaimReducedStake proto.InternalMessageInfo

func (m *MsgClaimReducedStake) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

type MsgClaimReducedStakeResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgClaimReducedStakeResponse) Reset()         { *m = MsgClaimReducedStakeResponse{} }
func (m *MsgClaimReducedStakeResponse) String() string { return proto.CompactTextString(m) }
func (*MsgClaimReducedStakeResponse) ProtoMessage()    {}
func (*MsgClaimReducedStakeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b77bc60185085f37, []int{13}
}
func (m *MsgClaimReducedStakeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgClaimReducedStakeResponse.Unmarshal(m, b)
}
func (m *MsgClaimReducedStakeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgClaimReducedStakeResponse.Marshal(b, m, deterministic)
}
func (m *MsgClaimReducedStakeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgClaimReducedStakeResponse.Merge(m, src)
}
func (m *MsgClaimReducedStakeResponse) XXX_Size() int {
	return xxx_messageInfo_MsgClaimReducedStakeResponse.Size(m)
}
func (m *MsgClaimReducedStakeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgClaimReducedStakeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgClaimReducedStakeResponse proto.InternalMessageInfo

type MsgSubmitAIChallengeResponse struct {
	Sender               string   `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	Epoch                uint64   `protobuf:"varint,2,opt,name=epoch,proto3" json:"epoch,omitempty"`
	CommitHash           string   `protobuf:"bytes,3,opt,name=commit_hash,json=commitHash,proto3" json:"commit_hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgSubmitAIChallengeResponse) Reset()         { *m = MsgSubmitAIChallengeResponse{} }
func (m *MsgSubmitAIChallengeResponse) String() string { return proto.CompactTextString(m) }
func (*MsgSubmitAIChallengeResponse) ProtoMessage()    {}
func (*MsgSubmitAIChallengeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b77bc60185085f37, []int{14}
}
func (m *MsgSubmitAIChallengeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgSubmitAIChallengeResponse.Unmarshal(m, b)
}
func (m *MsgSubmitAIChallengeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgSubmitAIChallengeResponse.Marshal(b, m, deterministic)
}
func (m *MsgSubmitAIChallengeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSubmitAIChallengeResponse.Merge(m, src)
}
func (m *MsgSubmitAIChallengeResponse) XXX_Size() int {
	return xxx_messageInfo_MsgSubmitAIChallengeResponse.Size(m)
}
func (m *MsgSubmitAIChallengeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSubmitAIChallengeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSubmitAIChallengeResponse proto.InternalMessageInfo

func (m *MsgSubmitAIChallengeResponse) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

func (m *MsgSubmitAIChallengeResponse) GetEpoch() uint64 {
	if m != nil {
		return m.Epoch
	}
	return 0
}

func (m *MsgSubmitAIChallengeResponse) GetCommitHash() string {
	if m != nil {
		return m.CommitHash
	}
	return ""
}

type MsgSubmitAIChallengeResponseResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgSubmitAIChallengeResponseResponse) Reset()         { *m = MsgSubmitAIChallengeResponseResponse{} }
func (m *MsgSubmitAIChallengeResponseResponse) String() string { return proto.CompactTextString(m) }
func (*MsgSubmitAIChallengeResponseResponse) ProtoMessage()    {}
func (*MsgSubmitAIChallengeResponseResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b77bc60185085f37, []int{15}
}
func (m *MsgSubmitAIChallengeResponseResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgSubmitAIChallengeResponseResponse.Unmarshal(m, b)
}
func (m *MsgSubmitAIChallengeResponseResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgSubmitAIChallengeResponseResponse.Marshal(b, m, deterministic)
}
func (m *MsgSubmitAIChallengeResponseResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSubmitAIChallengeResponseResponse.Merge(m, src)
}
func (m *MsgSubmitAIChallengeResponseResponse) XXX_Size() int {
	return xxx_messageInfo_MsgSubmitAIChallengeResponseResponse.Size(m)
}
func (m *MsgSubmitAIChallengeResponseResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSubmitAIChallengeResponseResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSubmitAIChallengeResponseResponse proto.InternalMessageInfo

type MsgRevealAIChallengeResponse struct {
	Sender               string   `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	Epoch                uint64   `protobuf:"varint,2,opt,name=epoch,proto3" json:"epoch,omitempty"`
	RevealData           string   `protobuf:"bytes,3,opt,name=reveal_data,json=revealData,proto3" json:"reveal_data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgRevealAIChallengeResponse) Reset()         { *m = MsgRevealAIChallengeResponse{} }
func (m *MsgRevealAIChallengeResponse) String() string { return proto.CompactTextString(m) }
func (*MsgRevealAIChallengeResponse) ProtoMessage()    {}
func (*MsgRevealAIChallengeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b77bc60185085f37, []int{16}
}
func (m *MsgRevealAIChallengeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgRevealAIChallengeResponse.Unmarshal(m, b)
}
func (m *MsgRevealAIChallengeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgRevealAIChallengeResponse.Marshal(b, m, deterministic)
}
func (m *MsgRevealAIChallengeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRevealAIChallengeResponse.Merge(m, src)
}
func (m *MsgRevealAIChallengeResponse) XXX_Size() int {
	return xxx_messageInfo_MsgRevealAIChallengeResponse.Size(m)
}
func (m *MsgRevealAIChallengeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRevealAIChallengeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRevealAIChallengeResponse proto.InternalMessageInfo

func (m *MsgRevealAIChallengeResponse) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

func (m *MsgRevealAIChallengeResponse) GetEpoch() uint64 {
	if m != nil {
		return m.Epoch
	}
	return 0
}

func (m *MsgRevealAIChallengeResponse) GetRevealData() string {
	if m != nil {
		return m.RevealData
	}
	return ""
}

type MsgRevealAIChallengeResponseResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgRevealAIChallengeResponseResponse) Reset()         { *m = MsgRevealAIChallengeResponseResponse{} }
func (m *MsgRevealAIChallengeResponseResponse) String() string { return proto.CompactTextString(m) }
func (*MsgRevealAIChallengeResponseResponse) ProtoMessage()    {}
func (*MsgRevealAIChallengeResponseResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b77bc60185085f37, []int{17}
}
func (m *MsgRevealAIChallengeResponseResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgRevealAIChallengeResponseResponse.Unmarshal(m, b)
}
func (m *MsgRevealAIChallengeResponseResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgRevealAIChallengeResponseResponse.Marshal(b, m, deterministic)
}
func (m *MsgRevealAIChallengeResponseResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRevealAIChallengeResponseResponse.Merge(m, src)
}
func (m *MsgRevealAIChallengeResponseResponse) XXX_Size() int {
	return xxx_messageInfo_MsgRevealAIChallengeResponseResponse.Size(m)
}
func (m *MsgRevealAIChallengeResponseResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRevealAIChallengeResponseResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRevealAIChallengeResponseResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgRegister)(nil), "axon.agent.v1.MsgRegister")
	proto.RegisterType((*MsgRegisterResponse)(nil), "axon.agent.v1.MsgRegisterResponse")
	proto.RegisterType((*MsgAddStake)(nil), "axon.agent.v1.MsgAddStake")
	proto.RegisterType((*MsgAddStakeResponse)(nil), "axon.agent.v1.MsgAddStakeResponse")
	proto.RegisterType((*MsgUpdateAgent)(nil), "axon.agent.v1.MsgUpdateAgent")
	proto.RegisterType((*MsgUpdateAgentResponse)(nil), "axon.agent.v1.MsgUpdateAgentResponse")
	proto.RegisterType((*MsgHeartbeat)(nil), "axon.agent.v1.MsgHeartbeat")
	proto.RegisterType((*MsgHeartbeatResponse)(nil), "axon.agent.v1.MsgHeartbeatResponse")
	proto.RegisterType((*MsgDeregister)(nil), "axon.agent.v1.MsgDeregister")
	proto.RegisterType((*MsgDeregisterResponse)(nil), "axon.agent.v1.MsgDeregisterResponse")
	proto.RegisterType((*MsgReduceStake)(nil), "axon.agent.v1.MsgReduceStake")
	proto.RegisterType((*MsgReduceStakeResponse)(nil), "axon.agent.v1.MsgReduceStakeResponse")
	proto.RegisterType((*MsgClaimReducedStake)(nil), "axon.agent.v1.MsgClaimReducedStake")
	proto.RegisterType((*MsgClaimReducedStakeResponse)(nil), "axon.agent.v1.MsgClaimReducedStakeResponse")
	proto.RegisterType((*MsgSubmitAIChallengeResponse)(nil), "axon.agent.v1.MsgSubmitAIChallengeResponse")
	proto.RegisterType((*MsgSubmitAIChallengeResponseResponse)(nil), "axon.agent.v1.MsgSubmitAIChallengeResponseResponse")
	proto.RegisterType((*MsgRevealAIChallengeResponse)(nil), "axon.agent.v1.MsgRevealAIChallengeResponse")
	proto.RegisterType((*MsgRevealAIChallengeResponseResponse)(nil), "axon.agent.v1.MsgRevealAIChallengeResponseResponse")
}

func init() { proto.RegisterFile("axon/agent/v1/tx.proto", fileDescriptor_b77bc60185085f37) }

var fileDescriptor_b77bc60185085f37 = []byte{
	// 702 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x56, 0xdd, 0x6e, 0xd3, 0x30,
	0x14, 0xa6, 0xdb, 0x5a, 0xb6, 0xd3, 0x0d, 0x89, 0x50, 0xba, 0x2e, 0xec, 0x4f, 0x61, 0xa0, 0x69,
	0x13, 0x09, 0xdd, 0x40, 0x48, 0x70, 0xc3, 0x7e, 0x2e, 0xb6, 0x49, 0x95, 0x50, 0x26, 0x84, 0xc4,
	0x4d, 0xe5, 0x24, 0x96, 0x63, 0x91, 0xc4, 0x55, 0xed, 0x56, 0x03, 0x09, 0x09, 0xf1, 0x2a, 0xbc,
	0xc0, 0x1e, 0x83, 0x07, 0xe0, 0x9a, 0xdb, 0xbd, 0x06, 0x8a, 0x93, 0x7a, 0x09, 0x4d, 0xba, 0x82,
	0x76, 0xd5, 0xf8, 0x7c, 0xe7, 0x7c, 0xe7, 0xfb, 0x6c, 0x1f, 0xab, 0xd0, 0x44, 0x17, 0x2c, 0xb2,
	0x10, 0xc1, 0x91, 0xb0, 0x86, 0x6d, 0x4b, 0x5c, 0x98, 0xbd, 0x3e, 0x13, 0x4c, 0x5b, 0x8a, 0xe3,
	0xa6, 0x8c, 0x9b, 0xc3, 0xb6, 0xbe, 0xec, 0x32, 0x1e, 0x32, 0x6e, 0x85, 0x9c, 0xc4, 0x69, 0x21,
	0x27, 0x49, 0x9e, 0xbe, 0x9e, 0x02, 0x0e, 0xe2, 0xd8, 0x1a, 0xb6, 0x1d, 0x2c, 0x50, 0xdb, 0x72,
	0x19, 0x8d, 0x52, 0xbc, 0x41, 0x18, 0x61, 0xf2, 0xd3, 0x8a, 0xbf, 0x92, 0xa8, 0xf1, 0xa3, 0x02,
	0xf5, 0x0e, 0x27, 0x36, 0x26, 0x94, 0x0b, 0xdc, 0xd7, 0x9a, 0x50, 0xe3, 0x38, 0xf2, 0x70, 0xbf,
	0x55, 0xd9, 0xac, 0x6c, 0x2f, 0xd8, 0xe9, 0x4a, 0x33, 0x60, 0xd1, 0x45, 0x3d, 0xe4, 0xd0, 0x80,
	0x0a, 0x8a, 0x79, 0x6b, 0x46, 0xa2, 0xb9, 0x98, 0xd6, 0x80, 0x6a, 0xc8, 0x3c, 0x1c, 0xb4, 0x66,
	0x25, 0x98, 0x2c, 0xb4, 0x97, 0x50, 0xe5, 0x02, 0x7d, 0xc2, 0xad, 0xb9, 0xcd, 0xca, 0x76, 0x7d,
	0x6f, 0xc5, 0x4c, 0x74, 0x9a, 0xb1, 0x4e, 0x33, 0xd5, 0x69, 0x1e, 0x31, 0x1a, 0x1d, 0xce, 0xfd,
	0xfc, 0xbd, 0x71, 0xc7, 0x4e, 0xb2, 0x5f, 0xd7, 0xbf, 0x5f, 0x5d, 0xee, 0xa4, 0xdd, 0x8d, 0xe7,
	0xf0, 0x20, 0x23, 0xd2, 0xc6, 0xbc, 0xc7, 0x22, 0x8e, 0xb5, 0x15, 0x98, 0x97, 0xfb, 0xd2, 0xa5,
	0x5e, 0x2a, 0xf7, 0xae, 0x5c, 0x9f, 0x7a, 0x06, 0x95, 0xb6, 0x0e, 0x3c, 0xef, 0x3c, 0x66, 0x2b,
	0xb5, 0xa5, 0xc4, 0xcd, 0xfc, 0xbf, 0xb8, 0x0f, 0x52, 0xdc, 0xa8, 0x95, 0x12, 0xf7, 0x16, 0xea,
	0x82, 0x09, 0x14, 0x74, 0x93, 0x06, 0x95, 0xe9, 0x1a, 0x80, 0xac, 0x91, 0x4c, 0x06, 0x83, 0x7b,
	0x1d, 0x4e, 0xde, 0xf7, 0x3c, 0x24, 0xf0, 0x41, 0xec, 0xeb, 0xf6, 0x4f, 0x27, 0xef, 0xa4, 0x05,
	0xcd, 0x7c, 0xc3, 0x91, 0x19, 0x63, 0x1f, 0x16, 0x3b, 0x9c, 0x9c, 0x60, 0xd4, 0x17, 0x0e, 0x46,
	0xa5, 0x42, 0xf2, 0x74, 0x4d, 0x68, 0x64, 0x8b, 0x14, 0xd9, 0x0b, 0x58, 0xea, 0x70, 0x72, 0x8c,
	0xfb, 0x37, 0x5c, 0xba, 0x3c, 0xdb, 0x32, 0x3c, 0xcc, 0x55, 0x29, 0xba, 0x48, 0x6e, 0x93, 0x8d,
	0xbd, 0x81, 0x8b, 0x27, 0x9f, 0xf6, 0x2b, 0xa8, 0xa1, 0x90, 0x0d, 0x22, 0x31, 0xed, 0x71, 0xa7,
	0xe9, 0x45, 0xbb, 0x94, 0xe9, 0xa7, 0x94, 0xbc, 0x91, 0x86, 0x8f, 0x02, 0x44, 0xc3, 0x04, 0x9e,
	0x7c, 0xfb, 0xf2, 0xb4, 0xeb, 0xb0, 0x5a, 0x54, 0xac, 0xc8, 0xbf, 0x48, 0xfc, 0x7c, 0xe0, 0x84,
	0x54, 0x1c, 0x9c, 0x1e, 0xf9, 0x28, 0x08, 0x70, 0x44, 0xae, 0xef, 0x5b, 0x99, 0xe9, 0x06, 0x54,
	0x71, 0x8f, 0xb9, 0xbe, 0xf4, 0x3c, 0x67, 0x27, 0x0b, 0x6d, 0x03, 0xea, 0x2e, 0x0b, 0x43, 0x2a,
	0xba, 0x3e, 0xe2, 0x7e, 0x7a, 0x27, 0x20, 0x09, 0x9d, 0x20, 0xee, 0xe7, 0xb5, 0x3d, 0x85, 0xad,
	0x49, 0xbd, 0xff, 0xd2, 0x68, 0xe3, 0x21, 0x46, 0xc1, 0xad, 0x68, 0xec, 0x4b, 0xaa, 0xae, 0x87,
	0x04, 0x1a, 0x69, 0x4c, 0x42, 0xc7, 0x48, 0xa0, 0x22, 0x8d, 0xa5, 0xbd, 0x47, 0xbf, 0x7b, 0xbf,
	0x6a, 0x30, 0xdb, 0xe1, 0x44, 0x3b, 0x83, 0x79, 0xf5, 0xea, 0xe9, 0x66, 0xee, 0x91, 0x35, 0x33,
	0x8f, 0x8d, 0x6e, 0x94, 0x63, 0xca, 0xd7, 0x19, 0xcc, 0xab, 0xa7, 0xa6, 0x80, 0x6b, 0x84, 0x15,
	0x71, 0x8d, 0xbd, 0x1b, 0xe7, 0x50, 0xcf, 0x8e, 0xfc, 0xda, 0x78, 0x49, 0x06, 0xd6, 0x9f, 0x4c,
	0x84, 0x15, 0x69, 0x07, 0x16, 0xae, 0x87, 0xf7, 0xd1, 0x78, 0x8d, 0x02, 0xf5, 0xc7, 0x13, 0x40,
	0x45, 0xf7, 0x0e, 0x20, 0x33, 0xbe, 0xab, 0xe3, 0x25, 0xd7, 0xa8, 0xbe, 0x35, 0x09, 0xcd, 0xba,
	0xce, 0x4e, 0xf0, 0x5a, 0xd1, 0xa6, 0x2b, 0xb8, 0xc8, 0x75, 0xc1, 0x3c, 0x6a, 0x18, 0xee, 0x8f,
	0x0f, 0x63, 0x81, 0xc1, 0xb1, 0x24, 0x7d, 0x77, 0x8a, 0x24, 0xd5, 0xe6, 0x2b, 0xac, 0x94, 0x8f,
	0x65, 0x01, 0x53, 0x69, 0xb2, 0xbe, 0xff, 0x0f, 0xc9, 0xd9, 0xf6, 0xe5, 0x13, 0xb7, 0x5b, 0xb4,
	0x53, 0x25, 0xc9, 0x45, 0xed, 0x6f, 0x9c, 0x27, 0xbd, 0xfa, 0xed, 0xea, 0x72, 0xa7, 0x72, 0xb8,
	0xf3, 0x71, 0x9b, 0x50, 0xe1, 0x0f, 0x1c, 0xd3, 0x65, 0xa1, 0x15, 0xf3, 0x3c, 0x73, 0x7d, 0x44,
	0x23, 0xf9, 0x69, 0x5d, 0xa4, 0x7f, 0x6c, 0xc4, 0xe7, 0x1e, 0xe6, 0x4e, 0x4d, 0xfe, 0xf7, 0xd8,
	0xff, 0x13, 0x00, 0x00, 0xff, 0xff, 0x1a, 0x53, 0x55, 0x91, 0xf3, 0x08, 0x00, 0x00,
}
