// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.1
// source: axon/agent/v1/tx.proto

package types

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Msg_Register_FullMethodName                  = "/axon.agent.v1.Msg/Register"
	Msg_AddStake_FullMethodName                  = "/axon.agent.v1.Msg/AddStake"
	Msg_UpdateAgent_FullMethodName               = "/axon.agent.v1.Msg/UpdateAgent"
	Msg_Heartbeat_FullMethodName                 = "/axon.agent.v1.Msg/Heartbeat"
	Msg_Deregister_FullMethodName                = "/axon.agent.v1.Msg/Deregister"
	Msg_ReduceStake_FullMethodName               = "/axon.agent.v1.Msg/ReduceStake"
	Msg_ClaimReducedStake_FullMethodName         = "/axon.agent.v1.Msg/ClaimReducedStake"
	Msg_SubmitAIChallengeResponse_FullMethodName = "/axon.agent.v1.Msg/SubmitAIChallengeResponse"
	Msg_RevealAIChallengeResponse_FullMethodName = "/axon.agent.v1.Msg/RevealAIChallengeResponse"
)

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MsgClient interface {
	Register(ctx context.Context, in *MsgRegister, opts ...grpc.CallOption) (*MsgRegisterResponse, error)
	AddStake(ctx context.Context, in *MsgAddStake, opts ...grpc.CallOption) (*MsgAddStakeResponse, error)
	UpdateAgent(ctx context.Context, in *MsgUpdateAgent, opts ...grpc.CallOption) (*MsgUpdateAgentResponse, error)
	Heartbeat(ctx context.Context, in *MsgHeartbeat, opts ...grpc.CallOption) (*MsgHeartbeatResponse, error)
	Deregister(ctx context.Context, in *MsgDeregister, opts ...grpc.CallOption) (*MsgDeregisterResponse, error)
	ReduceStake(ctx context.Context, in *MsgReduceStake, opts ...grpc.CallOption) (*MsgReduceStakeResponse, error)
	ClaimReducedStake(ctx context.Context, in *MsgClaimReducedStake, opts ...grpc.CallOption) (*MsgClaimReducedStakeResponse, error)
	SubmitAIChallengeResponse(ctx context.Context, in *MsgSubmitAIChallengeResponse, opts ...grpc.CallOption) (*MsgSubmitAIChallengeResponseResponse, error)
	RevealAIChallengeResponse(ctx context.Context, in *MsgRevealAIChallengeResponse, opts ...grpc.CallOption) (*MsgRevealAIChallengeResponseResponse, error)
}

type msgClient struct {
	cc grpc.ClientConnInterface
}

func NewMsgClient(cc grpc.ClientConnInterface) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) Register(ctx context.Context, in *MsgRegister, opts ...grpc.CallOption) (*MsgRegisterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgRegisterResponse)
	err := c.cc.Invoke(ctx, Msg_Register_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) AddStake(ctx context.Context, in *MsgAddStake, opts ...grpc.CallOption) (*MsgAddStakeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgAddStakeResponse)
	err := c.cc.Invoke(ctx, Msg_AddStake_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) UpdateAgent(ctx context.Context, in *MsgUpdateAgent, opts ...grpc.CallOption) (*MsgUpdateAgentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgUpdateAgentResponse)
	err := c.cc.Invoke(ctx, Msg_UpdateAgent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) Heartbeat(ctx context.Context, in *MsgHeartbeat, opts ...grpc.CallOption) (*MsgHeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgHeartbeatResponse)
	err := c.cc.Invoke(ctx, Msg_Heartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) Deregister(ctx context.Context, in *MsgDeregister, opts ...grpc.CallOption) (*MsgDeregisterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgDeregisterResponse)
	err := c.cc.Invoke(ctx, Msg_Deregister_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) ReduceStake(ctx context.Context, in *MsgReduceStake, opts ...grpc.CallOption) (*MsgReduceStakeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgReduceStakeResponse)
	err := c.cc.Invoke(ctx, Msg_ReduceStake_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) ClaimReducedStake(ctx context.Context, in *MsgClaimReducedStake, opts ...grpc.CallOption) (*MsgClaimReducedStakeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgClaimReducedStakeResponse)
	err := c.cc.Invoke(ctx, Msg_ClaimReducedStake_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) SubmitAIChallengeResponse(ctx context.Context, in *MsgSubmitAIChallengeResponse, opts ...grpc.CallOption) (*MsgSubmitAIChallengeResponseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgSubmitAIChallengeResponseResponse)
	err := c.cc.Invoke(ctx, Msg_SubmitAIChallengeResponse_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) RevealAIChallengeResponse(ctx context.Context, in *MsgRevealAIChallengeResponse, opts ...grpc.CallOption) (*MsgRevealAIChallengeResponseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgRevealAIChallengeResponseResponse)
	err := c.cc.Invoke(ctx, Msg_RevealAIChallengeResponse_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
// All implementations must embed UnimplementedMsgServer
// for forward compatibility.
type MsgServer interface {
	Register(context.Context, *MsgRegister) (*MsgRegisterResponse, error)
	AddStake(context.Context, *MsgAddStake) (*MsgAddStakeResponse, error)
	UpdateAgent(context.Context, *MsgUpdateAgent) (*MsgUpdateAgentResponse, error)
	Heartbeat(context.Context, *MsgHeartbeat) (*MsgHeartbeatResponse, error)
	Deregister(context.Context, *MsgDeregister) (*MsgDeregisterResponse, error)
	ReduceStake(context.Context, *MsgReduceStake) (*MsgReduceStakeResponse, error)
	ClaimReducedStake(context.Context, *MsgClaimReducedStake) (*MsgClaimReducedStakeResponse, error)
	SubmitAIChallengeResponse(context.Context, *MsgSubmitAIChallengeResponse) (*MsgSubmitAIChallengeResponseResponse, error)
	RevealAIChallengeResponse(context.Context, *MsgRevealAIChallengeResponse) (*MsgRevealAIChallengeResponseResponse, error)
	mustEmbedUnimplementedMsgServer()
}

// UnimplementedMsgServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMsgServer struct{}

func (UnimplementedMsgServer) Register(context.Context, *MsgRegister) (*MsgRegisterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedMsgServer) AddStake(context.Context, *MsgAddStake) (*MsgAddStakeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddStake not implemented")
}
func (UnimplementedMsgServer) UpdateAgent(context.Context, *MsgUpdateAgent) (*MsgUpdateAgentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateAgent not implemented")
}
func (UnimplementedMsgServer) Heartbeat(context.Context, *MsgHeartbeat) (*MsgHeartbeatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedMsgServer) Deregister(context.Context, *MsgDeregister) (*MsgDeregisterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Deregister not implemented")
}
func (UnimplementedMsgServer) ReduceStake(context.Context, *MsgReduceStake) (*MsgReduceStakeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReduceStake not implemented")
}
func (UnimplementedMsgServer) ClaimReducedStake(context.Context, *MsgClaimReducedStake) (*MsgClaimReducedStakeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ClaimReducedStake not implemented")
}
func (UnimplementedMsgServer) SubmitAIChallengeResponse(context.Context, *MsgSubmitAIChallengeResponse) (*MsgSubmitAIChallengeResponseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitAIChallengeResponse not implemented")
}
func (UnimplementedMsgServer) RevealAIChallengeResponse(context.Context, *MsgRevealAIChallengeResponse) (*MsgRevealAIChallengeResponseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RevealAIChallengeResponse not implemented")
}
func (UnimplementedMsgServer) mustEmbedUnimplementedMsgServer() {}
func (UnimplementedMsgServer) testEmbeddedByValue()             {}

// UnsafeMsgServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MsgServer will
// result in compilation errors.
type UnsafeMsgServer interface {
	mustEmbedUnimplementedMsgServer()
}

func RegisterMsgServer(s grpc.ServiceRegistrar, srv MsgServer) {
	// If the following call panics, it indicates UnimplementedMsgServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Msg_ServiceDesc, srv)
}

func _Msg_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRegister)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).Register(ctx, req.(*MsgRegister))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_AddStake_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgAddStake)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).AddStake(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_AddStake_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).AddStake(ctx, req.(*MsgAddStake))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_UpdateAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateAgent)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_UpdateAgent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateAgent(ctx, req.(*MsgUpdateAgent))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgHeartbeat)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_Heartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).Heartbeat(ctx, req.(*MsgHeartbeat))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_Deregister_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgDeregister)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).Deregister(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_Deregister_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).Deregister(ctx, req.(*MsgDeregister))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_ReduceStake_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgReduceStake)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).ReduceStake(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_ReduceStake_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).ReduceStake(ctx, req.(*MsgReduceStake))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_ClaimReducedStake_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgClaimReducedStake)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).ClaimReducedStake(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_ClaimReducedStake_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).ClaimReducedStake(ctx, req.(*MsgClaimReducedStake))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_SubmitAIChallengeResponse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSubmitAIChallengeResponse)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SubmitAIChallengeResponse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_SubmitAIChallengeResponse_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SubmitAIChallengeResponse(ctx, req.(*MsgSubmitAIChallengeResponse))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_RevealAIChallengeResponse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRevealAIChallengeResponse)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).RevealAIChallengeResponse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_RevealAIChallengeResponse_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).RevealAIChallengeResponse(ctx, req.(*MsgRevealAIChallengeResponse))
	}
	return interceptor(ctx, in, info, handler)
}

// Msg_ServiceDesc is the grpc.ServiceDesc for Msg service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Msg_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "axon.agent.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _Msg_Register_Handler,
		},
		{
			MethodName: "AddStake",
			Handler:    _Msg_AddStake_Handler,
		},
		{
			MethodName: "UpdateAgent",
			Handler:    _Msg_UpdateAgent_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _Msg_Heartbeat_Handler,
		},
		{
			MethodName: "Deregister",
			Handler:    _Msg_Deregister_Handler,
		},
		{
			MethodName: "ReduceStake",
			Handler:    _Msg_ReduceStake_Handler,
		},
		{
			MethodName: "ClaimReducedStake",
			Handler:    _Msg_ClaimReducedStake_Handler,
		},
		{
			MethodName: "SubmitAIChallengeResponse",
			Handler:    _Msg_SubmitAIChallengeResponse_Handler,
		},
		{
			MethodName: "RevealAIChallengeResponse",
			Handler:    _Msg_RevealAIChallengeResponse_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "axon/agent/v1/tx.proto",
}
